// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package twitch.users.email;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateEmailRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:twitch.users.email.UpdateEmailRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <code>string new_email = 2;</code>
     */
    java.lang.String getNewEmail();
    /**
     * <code>string new_email = 2;</code>
     */
    com.google.protobuf.ByteString
        getNewEmailBytes();
  }
  /**
   * Protobuf type {@code twitch.users.email.UpdateEmailRequest}
   */
  public  static final class UpdateEmailRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:twitch.users.email.UpdateEmailRequest)
      UpdateEmailRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateEmailRequest.newBuilder() to construct.
    private UpdateEmailRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateEmailRequest() {
      userId_ = 0L;
      newEmail_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateEmailRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              newEmail_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              twitch.users.email.Test.UpdateEmailRequest.class, twitch.users.email.Test.UpdateEmailRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int NEW_EMAIL_FIELD_NUMBER = 2;
    private volatile java.lang.Object newEmail_;
    /**
     * <code>string new_email = 2;</code>
     */
    public java.lang.String getNewEmail() {
      java.lang.Object ref = newEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newEmail_ = s;
        return s;
      }
    }
    /**
     * <code>string new_email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewEmailBytes() {
      java.lang.Object ref = newEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!getNewEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newEmail_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!getNewEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newEmail_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof twitch.users.email.Test.UpdateEmailRequest)) {
        return super.equals(obj);
      }
      twitch.users.email.Test.UpdateEmailRequest other = (twitch.users.email.Test.UpdateEmailRequest) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getNewEmail()
          .equals(other.getNewEmail());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + NEW_EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getNewEmail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static twitch.users.email.Test.UpdateEmailRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(twitch.users.email.Test.UpdateEmailRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code twitch.users.email.UpdateEmailRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:twitch.users.email.UpdateEmailRequest)
        twitch.users.email.Test.UpdateEmailRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                twitch.users.email.Test.UpdateEmailRequest.class, twitch.users.email.Test.UpdateEmailRequest.Builder.class);
      }

      // Construct using twitch.users.email.Test.UpdateEmailRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        newEmail_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailRequest_descriptor;
      }

      public twitch.users.email.Test.UpdateEmailRequest getDefaultInstanceForType() {
        return twitch.users.email.Test.UpdateEmailRequest.getDefaultInstance();
      }

      public twitch.users.email.Test.UpdateEmailRequest build() {
        twitch.users.email.Test.UpdateEmailRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public twitch.users.email.Test.UpdateEmailRequest buildPartial() {
        twitch.users.email.Test.UpdateEmailRequest result = new twitch.users.email.Test.UpdateEmailRequest(this);
        result.userId_ = userId_;
        result.newEmail_ = newEmail_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof twitch.users.email.Test.UpdateEmailRequest) {
          return mergeFrom((twitch.users.email.Test.UpdateEmailRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(twitch.users.email.Test.UpdateEmailRequest other) {
        if (other == twitch.users.email.Test.UpdateEmailRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getNewEmail().isEmpty()) {
          newEmail_ = other.newEmail_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        twitch.users.email.Test.UpdateEmailRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (twitch.users.email.Test.UpdateEmailRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object newEmail_ = "";
      /**
       * <code>string new_email = 2;</code>
       */
      public java.lang.String getNewEmail() {
        java.lang.Object ref = newEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          newEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string new_email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNewEmailBytes() {
        java.lang.Object ref = newEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string new_email = 2;</code>
       */
      public Builder setNewEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        newEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string new_email = 2;</code>
       */
      public Builder clearNewEmail() {
        
        newEmail_ = getDefaultInstance().getNewEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string new_email = 2;</code>
       */
      public Builder setNewEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        newEmail_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:twitch.users.email.UpdateEmailRequest)
    }

    // @@protoc_insertion_point(class_scope:twitch.users.email.UpdateEmailRequest)
    private static final twitch.users.email.Test.UpdateEmailRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new twitch.users.email.Test.UpdateEmailRequest();
    }

    public static twitch.users.email.Test.UpdateEmailRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateEmailRequest>
        PARSER = new com.google.protobuf.AbstractParser<UpdateEmailRequest>() {
      public UpdateEmailRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateEmailRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateEmailRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateEmailRequest> getParserForType() {
      return PARSER;
    }

    public twitch.users.email.Test.UpdateEmailRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateEmailResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:twitch.users.email.UpdateEmailResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * EmailBoss may clean up the email it receives to trim whitespace
     * or remove superfluous characters. The cleaned_email will be the
     * email actually stored after this cleaning.
     * </pre>
     *
     * <code>string cleaned_email = 1;</code>
     */
    java.lang.String getCleanedEmail();
    /**
     * <pre>
     * EmailBoss may clean up the email it receives to trim whitespace
     * or remove superfluous characters. The cleaned_email will be the
     * email actually stored after this cleaning.
     * </pre>
     *
     * <code>string cleaned_email = 1;</code>
     */
    com.google.protobuf.ByteString
        getCleanedEmailBytes();
  }
  /**
   * Protobuf type {@code twitch.users.email.UpdateEmailResponse}
   */
  public  static final class UpdateEmailResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:twitch.users.email.UpdateEmailResponse)
      UpdateEmailResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateEmailResponse.newBuilder() to construct.
    private UpdateEmailResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateEmailResponse() {
      cleanedEmail_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateEmailResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cleanedEmail_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              twitch.users.email.Test.UpdateEmailResponse.class, twitch.users.email.Test.UpdateEmailResponse.Builder.class);
    }

    public static final int CLEANED_EMAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object cleanedEmail_;
    /**
     * <pre>
     * EmailBoss may clean up the email it receives to trim whitespace
     * or remove superfluous characters. The cleaned_email will be the
     * email actually stored after this cleaning.
     * </pre>
     *
     * <code>string cleaned_email = 1;</code>
     */
    public java.lang.String getCleanedEmail() {
      java.lang.Object ref = cleanedEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cleanedEmail_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * EmailBoss may clean up the email it receives to trim whitespace
     * or remove superfluous characters. The cleaned_email will be the
     * email actually stored after this cleaning.
     * </pre>
     *
     * <code>string cleaned_email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCleanedEmailBytes() {
      java.lang.Object ref = cleanedEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cleanedEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCleanedEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cleanedEmail_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCleanedEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cleanedEmail_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof twitch.users.email.Test.UpdateEmailResponse)) {
        return super.equals(obj);
      }
      twitch.users.email.Test.UpdateEmailResponse other = (twitch.users.email.Test.UpdateEmailResponse) obj;

      boolean result = true;
      result = result && getCleanedEmail()
          .equals(other.getCleanedEmail());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLEANED_EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getCleanedEmail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static twitch.users.email.Test.UpdateEmailResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(twitch.users.email.Test.UpdateEmailResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code twitch.users.email.UpdateEmailResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:twitch.users.email.UpdateEmailResponse)
        twitch.users.email.Test.UpdateEmailResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                twitch.users.email.Test.UpdateEmailResponse.class, twitch.users.email.Test.UpdateEmailResponse.Builder.class);
      }

      // Construct using twitch.users.email.Test.UpdateEmailResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cleanedEmail_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return twitch.users.email.Test.internal_static_twitch_users_email_UpdateEmailResponse_descriptor;
      }

      public twitch.users.email.Test.UpdateEmailResponse getDefaultInstanceForType() {
        return twitch.users.email.Test.UpdateEmailResponse.getDefaultInstance();
      }

      public twitch.users.email.Test.UpdateEmailResponse build() {
        twitch.users.email.Test.UpdateEmailResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public twitch.users.email.Test.UpdateEmailResponse buildPartial() {
        twitch.users.email.Test.UpdateEmailResponse result = new twitch.users.email.Test.UpdateEmailResponse(this);
        result.cleanedEmail_ = cleanedEmail_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof twitch.users.email.Test.UpdateEmailResponse) {
          return mergeFrom((twitch.users.email.Test.UpdateEmailResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(twitch.users.email.Test.UpdateEmailResponse other) {
        if (other == twitch.users.email.Test.UpdateEmailResponse.getDefaultInstance()) return this;
        if (!other.getCleanedEmail().isEmpty()) {
          cleanedEmail_ = other.cleanedEmail_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        twitch.users.email.Test.UpdateEmailResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (twitch.users.email.Test.UpdateEmailResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object cleanedEmail_ = "";
      /**
       * <pre>
       * EmailBoss may clean up the email it receives to trim whitespace
       * or remove superfluous characters. The cleaned_email will be the
       * email actually stored after this cleaning.
       * </pre>
       *
       * <code>string cleaned_email = 1;</code>
       */
      public java.lang.String getCleanedEmail() {
        java.lang.Object ref = cleanedEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cleanedEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * EmailBoss may clean up the email it receives to trim whitespace
       * or remove superfluous characters. The cleaned_email will be the
       * email actually stored after this cleaning.
       * </pre>
       *
       * <code>string cleaned_email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCleanedEmailBytes() {
        java.lang.Object ref = cleanedEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cleanedEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * EmailBoss may clean up the email it receives to trim whitespace
       * or remove superfluous characters. The cleaned_email will be the
       * email actually stored after this cleaning.
       * </pre>
       *
       * <code>string cleaned_email = 1;</code>
       */
      public Builder setCleanedEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cleanedEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * EmailBoss may clean up the email it receives to trim whitespace
       * or remove superfluous characters. The cleaned_email will be the
       * email actually stored after this cleaning.
       * </pre>
       *
       * <code>string cleaned_email = 1;</code>
       */
      public Builder clearCleanedEmail() {
        
        cleanedEmail_ = getDefaultInstance().getCleanedEmail();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * EmailBoss may clean up the email it receives to trim whitespace
       * or remove superfluous characters. The cleaned_email will be the
       * email actually stored after this cleaning.
       * </pre>
       *
       * <code>string cleaned_email = 1;</code>
       */
      public Builder setCleanedEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cleanedEmail_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:twitch.users.email.UpdateEmailResponse)
    }

    // @@protoc_insertion_point(class_scope:twitch.users.email.UpdateEmailResponse)
    private static final twitch.users.email.Test.UpdateEmailResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new twitch.users.email.Test.UpdateEmailResponse();
    }

    public static twitch.users.email.Test.UpdateEmailResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateEmailResponse>
        PARSER = new com.google.protobuf.AbstractParser<UpdateEmailResponse>() {
      public UpdateEmailResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateEmailResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateEmailResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateEmailResponse> getParserForType() {
      return PARSER;
    }

    public twitch.users.email.Test.UpdateEmailResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_twitch_users_email_UpdateEmailRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_twitch_users_email_UpdateEmailRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_twitch_users_email_UpdateEmailResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_twitch_users_email_UpdateEmailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\022twitch.users.email\"8\n\022Upda" +
      "teEmailRequest\022\017\n\007user_id\030\001 \001(\003\022\021\n\tnew_e" +
      "mail\030\002 \001(\t\",\n\023UpdateEmailResponse\022\025\n\rcle" +
      "aned_email\030\001 \001(\t2k\n\tEmailBoss\022^\n\013UpdateE" +
      "mail\022&.twitch.users.email.UpdateEmailReq" +
      "uest\032\'.twitch.users.email.UpdateEmailRes" +
      "ponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_twitch_users_email_UpdateEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_twitch_users_email_UpdateEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_twitch_users_email_UpdateEmailRequest_descriptor,
        new java.lang.String[] { "UserId", "NewEmail", });
    internal_static_twitch_users_email_UpdateEmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_twitch_users_email_UpdateEmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_twitch_users_email_UpdateEmailResponse_descriptor,
        new java.lang.String[] { "CleanedEmail", });
  }

  @javax.ws.rs.ext.Provider
  @javax.ws.rs.Produces({"application/protobuf", "application/json"})
  @javax.ws.rs.Consumes({"application/protobuf", "application/json"})
  public static class ProtoBufMessageProvider implements javax.ws.rs.ext.MessageBodyWriter<com.google.protobuf.Message>, javax.ws.rs.ext.MessageBodyReader<com.google.protobuf.Message> {
  
          @Override
          public boolean isWriteable(Class<?> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType) {
              return com.google.protobuf.Message.class.isAssignableFrom(type) && ("json".equals(mediaType.getSubtype()) || "protobuf".equals(mediaType.getSubtype()));
          }
  
          @Override
          public long getSize(com.google.protobuf.Message t, Class<?> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType) {
              if (t == null) {
                  return -1;
              }
              java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
              try {
                  writeTo(t, type, genericType, annotations, mediaType, null, out);
              } catch (java.io.IOException e) {
                  return -1;
              }
              return out.size();
          }
  
          @Override
          public void writeTo(com.google.protobuf.Message t, Class<?> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType, javax.ws.rs.core.MultivaluedMap<String, Object> httpHeaders, java.io.OutputStream entityStream) throws java.io.IOException, javax.ws.rs.WebApplicationException {
              switch (mediaType.getSubtype()) {
                  case "protobuf":
                      t.writeTo(entityStream);
                      break;
                  case "json":
                      entityStream.write(com.google.protobuf.util.JsonFormat.printer().print(t).getBytes("UTF-8"));
                      break;
                  default:
                      throw new javax.ws.rs.WebApplicationException("MediaType not supported!");
              }
  
          }
  
          @Override
          public boolean isReadable(Class<?> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType) {
              return com.google.protobuf.Message.class.isAssignableFrom(type) && ("json".equals(mediaType.getSubtype()) || "protobuf".equals(mediaType.getSubtype()));
          }
  
          @Override
          public com.google.protobuf.Message readFrom(Class<com.google.protobuf.Message> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType, javax.ws.rs.core.MultivaluedMap<String, String> httpHeaders, java.io.InputStream entityStream) throws java.io.IOException, javax.ws.rs.WebApplicationException {
              try {
                  switch (mediaType.getSubtype()) {
                      case "protobuf":
                          java.lang.reflect.Method m = type.getMethod("parseFrom", java.io.InputStream.class);
                          return (com.google.protobuf.Message) m.invoke(null, entityStream);
                      case "json":
                          com.google.protobuf.Message.Builder msg = (com.google.protobuf.Message.Builder)type.getMethod("newBuilder").invoke(null);
                          com.google.protobuf.util.JsonFormat.parser().merge(new java.io.InputStreamReader(entityStream), msg);
                          return msg.build();
                      default:
                          throw new javax.ws.rs.WebApplicationException("MediaType not supported!");
                  }
              } catch (Exception e) {
                  throw new javax.ws.rs.WebApplicationException(e);
              }
          }
  }
  
  @javax.ws.rs.Path( "/twitch.users.email.EmailBoss" )
  public interface EmailBoss {
    @javax.ws.rs.POST
    @javax.ws.rs.Path( "/UpdateEmail" )
    @javax.ws.rs.Consumes({"application/protobuf", "application/json"})
    @javax.ws.rs.Produces({"application/protobuf", "application/json"})
    twitch.users.email.Test.UpdateEmailResponse updateEmail(twitch.users.email.Test.UpdateEmailRequest request);
  }
  
  public static class EmailBossClient implements twitch.users.email.Test.EmailBoss {
    private final javax.ws.rs.client.WebTarget target;
  
    public EmailBossClient(javax.ws.rs.client.WebTarget target) {
      this.target = target.path("twitch.users.email.EmailBoss");
      this.target.register(new twitch.users.email.Test.ProtoBufMessageProvider());
    }
  
    private <R> R call(String path, com.google.protobuf.Message req, Class<R> responseClass) {
      javax.ws.rs.core.Response response = target.path(path)
          .request("application/protobuf")
          .post(javax.ws.rs.client.Entity.entity(req, "application/protobuf"));
  	 if (response.getStatusInfo().getFamily() == javax.ws.rs.core.Response.Status.Family.SUCCESSFUL) {
          R r = response.readEntity(responseClass);
          response.close();
          return r;
      } else {
          throw new javax.ws.rs.WebApplicationException(response);
      }
    }
  
  
    @Override
    public twitch.users.email.Test.UpdateEmailResponse updateEmail(twitch.users.email.Test.UpdateEmailRequest request) {
      return call("/UpdateEmail", request, twitch.users.email.Test.UpdateEmailResponse.class);
    }
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
